#!/bin/sh

usage () {
  printf 'Usage: scripts/build [-h]'
}

rebuild () {
  printf '[scripts/build] rebuilding native deps \n'
  electron_version="$(electron --version | sed s/v//)"
  electron_abi="$(electron --abi)"
  npm rebuild \
    --runtime=electron \
    --target="$electron_version" \
    --disturl=https://atom.io/download/atom-shell \
    --abi="$electron_abi" > /dev/null
}

build_css () {
  printf '[scripts/build] building css\n'
  node-sass \
    --importer node_modules/node-sass-magic-importer \
    --include-path app/scss scss/main.scss public/css/main.css \
    > /dev/null
}

build_background () {
  printf '[scripts/build] building background\n'
  tiffutil \
    -cathidpicheck \
    build/background.png build/background\@2x.png \
    -out build/background.tiff
}

postinstall () {
  printf '[scripts/build] installing app deps \n'
  build_css
  build_background
  rebuild
}

# parse CLI flags
while true; do
  case "$1" in
    rebuild ) shift; rebuild; break ;;
    css ) shift; build_css; break ;;
    background ) shift; build_background; break ;;
    postinstall ) shift; postinstall; break ;;
    * ) usage; break ;;
  esac
done
