#!/bin/bash

usage () {
  printf 'Usage: scripts/build [-h]'
}

rebuild () {
  electron_version="$(electron --version | sed s/v//)"
  electron_abi="$(electron --abi)"
  printf '[scripts/build] rebuilding native deps\n'
  printf '[scripts/build] detected electron=%s abi=%s\n' "$electron_version" "$electron_abi"
  npm rebuild \
    --runtime=electron \
    --target="$electron_version" \
    --disturl=https://atom.io/download/atom-shell \
    --abi="$electron_abi" \
    > /dev/null
}

build_background () {
  printf '[scripts/build] building background\n'
  tiffutil \
    -cathidpicheck \
    build/background.png build/background\@2x.png \
    -out build/background.tiff
}

bundle () {
  printf '[scripts/build] bundling javascript \n'
  node scripts/browserify.js
}

postinstall () {
  printf '[scripts/build] installing app deps \n'
  [ `uname` == 'Darwin' ] && build_background
  rebuild || exit 1
  bundle
}

# parse CLI flags
while true; do
  case "$1" in
    rebuild ) shift; rebuild; break ;;
    css ) shift; break ;;
    background ) shift; build_background; break ;;
    bundle ) shift; bundle; break ;;
    postinstall ) shift; postinstall; break ;;
    * ) usage; break ;;
  esac
done
